# Generated by Django 5.2.7 on 2025-12-04 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Displayed price (informational; Stripe is source of truth).', max_digits=10)),
                ('duration_days', models.IntegerField(blank=True, help_text='Optional for non-Stripe, fixed-duration access.', null=True)),
                ('features', models.JSONField(default=list, help_text='List/JSON of feature flags.')),
                ('plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('free', 'Free')], db_index=True, default='free', max_length=20)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe recurring price id (price_...). Required for paid plans.', max_length=200, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
            ],
            options={
                'ordering': ['price', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='plan_price_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('plan_type', 'free'), ('price', 0)), models.Q(('plan_type', 'free'), _negated=True), _connector='OR'), name='free_plan_price_zero')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_renewed', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, default='active', max_length=50)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payment.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'indexes': [models.Index(fields=['user'], name='payment_use_user_id_390130_idx'), models.Index(fields=['stripe_subscription_id'], name='payment_use_stripe__37a2db_idx'), models.Index(fields=['status', 'is_active'], name='payment_use_status_3679e5_idx')],
            },
        ),
    ]
