# Generated by Django 5.2.7 on 2025-11-10 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('medical_records', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('adoption_documents', models.FileField(blank=True, null=True, upload_to='adoption_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
