# Generated by Django 5.2.7 on 2026-04-04 03:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('playfulness_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_records', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('adoption_documents', models.FileField(blank=True, null=True, upload_to='adoption_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('snooze', 'Snooze'), ('walking', 'Walking'), ('playing', 'Playing')], default='snooze', max_length=20)),
                ('points', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='pet_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
                ('stars', models.ManyToManyField(blank=True, related_name='starred_pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('data', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cancellation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('required_items', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('enrolled_pets', models.ManyToManyField(blank=True, related_name='events', to='pet.petinfo')),
            ],
        ),
    ]
