# Generated by Django 5.2.7 on 2025-12-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='breed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
