# Generated by Django 5.2.7 on 2025-11-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_petinfo_location_petinfo_playfulness_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='petinfo',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
    ]
