# Generated by Django 5.2.7 on 2025-12-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_petinfo_gender_alter_petinfo_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
        ),
    ]
