# Generated by Django 5.2.7 on 2025-11-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_petinfo_gender_alter_petinfo_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinfo',
            old_name='image',
            new_name='image0',
        ),
        migrations.RenameField(
            model_name='petinfo',
            old_name='image5',
            new_name='image1',
        ),
        migrations.RemoveField(
            model_name='petinfo',
            name='image6',
        ),
    ]
