# Generated by Django 5.2.7 on 2025-11-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_rename_image_petinfo_image0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinfo',
            old_name='image0',
            new_name='image',
        ),
        migrations.AddField(
            model_name='petinfo',
            name='status',
            field=models.CharField(choices=[('snooze', 'Snooze'), ('walking', 'Walking'), ('playing', 'Playing')], default='snooze'),
        ),
    ]
