# Generated by Django 5.2.7 on 2025-11-24 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_rename_image0_petinfo_image_petinfo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petinfo',
            name='age',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='petinfo',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petinfo',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='starred_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
