# Generated by Django 4.2.11 on 2025-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_petinfo_age_petinfo_points_petinfo_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petinfo',
            name='status',
            field=models.CharField(choices=[('snooze', 'Snooze'), ('walking', 'Walking'), ('playing', 'Playing')], default='snooze', max_length=20),
        ),
    ]
