# Generated by Django 5.2.7 on 2025-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_petinfo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='petinfo',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
