# Generated by Django 5.2.7 on 2025-11-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_remove_petinfo_age_petinfo_birth_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petinfo',
            old_name='birth_day',
            new_name='date_of_birth',
        ),
    ]
