# Generated by Django 5.2.7 on 2025-11-10 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='share_info',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProfessionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=10)),
                ('about', models.TextField(max_length=500)),
                ('dog_size_worked_with', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('all', 'All')], default='all', max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_info', to='authentication.profile')),
            ],
        ),
    ]
