# Generated by Django 5.2.7 on 2025-11-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_emailverification_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='playfulness_level',
        ),
    ]
