# Generated by Django 5.2.7 on 2025-11-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dog_name',
        ),
    ]
