# Generated by Django 5.2.7 on 2025-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='professionalinformation',
            name='dog_size_worked_with',
        ),
        migrations.AddField(
            model_name='professionalinformation',
            name='dog_size_worked_with',
            field=models.ManyToManyField(related_name='professionals', to='authentication.dogsize'),
        ),
    ]
