# Generated by Django 5.2.7 on 2025-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_dogsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalinformation',
            name='dog_size_worked_with',
        ),
        migrations.DeleteModel(
            name='DogSize',
        ),
        migrations.AddField(
            model_name='professionalinformation',
            name='dog_size_worked_with',
            field=models.CharField(blank=True, help_text="Comma-separated dog sizes (e.g., 'small', 'small, large', 'small, large, medium')", max_length=200, null=True),
        ),
    ]
