# Generated by Django 5.2.7 on 2025-12-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_professionalinformation_dog_size_worked_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_dog_profile',
            field=models.BooleanField(default=False, help_text='Indicates if user has completed dog profile setup'),
        ),
    ]
