# Generated by Django 6.0 on 2025-12-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_profile_has_dog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalinformation',
            name='dog_size_worked_with',
            field=models.CharField(blank=True, help_text="Comma-separated dog sizes (e.g., 'Small', 'Small, Large', 'Small, Large, Medium')", max_length=200, null=True),
        ),
    ]
