# Generated by Django 5.2.7 on 2026-01-19 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_profile_latitude_remove_profile_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='authenticat_user_id_90ea9e_idx',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Prevents reuse of the same code after successful verification'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time this code was (re)sent to the user', null=True),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'code', 'is_used'], name='authenticat_user_id_91131e_idx'),
        ),
    ]
