# Generated by Django 5.2.7 on 2026-01-19 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_emailverification_authenticat_user_id_90ea9e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailverification',
            name='authenticat_user_id_91131e_idx',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='last_sent_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'code'], name='authenticat_user_id_90ea9e_idx'),
        ),
    ]
