# Generated by Django 5.2.7 on 2025-11-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
    ]
