# Generated by Django 5.2.7 on 2025-11-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_chatmessage_options_remove_chatmessage_is_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
