# Generated by Django 5.2.7 on 2025-11-29 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='room_name',
        ),
    ]
