# Generated by Django 5.2.7 on 2026-01-20 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_chatgroup_groupmessage_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='last_read_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
