# Generated by Django 5.2.7 on 2026-01-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_chatgroup_image_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
